# Generated by Django 3.2.6 on 2021-08-07 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('G', 'Generator'), ('H', 'Handwritten')], default='G', max_length=1)),
                ('data', models.CharField(max_length=256)),
                ('p_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.FilePathField(allow_files=False, allow_folders=True, max_length=64, path='/mnt/e/repos/dmojgon')),
                ('init_yml_extra', models.CharField(max_length=1024)),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('last_modified', models.DateTimeField()),
                ('validator_src', models.FilePathField(max_length=64, null=True, path=models.FilePathField(allow_files=False, allow_folders=True, max_length=64, path='/mnt/e/repos/dmojgon'), recursive=True)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='p_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.problem'),
        ),
    ]
